export const AuditActions = {
  // FUNCIONALES
  AFILIADO_BUSQUEDA: "AFILIADO_BUSQUEDA",
  AFILIADO_SUSPENDIDO: "AFILIADO_SUSPENDIDO",
  AFILIADO_INACTIVO: "AFILIADO_INACTIVO",

  // LOGIN/LOGOUT PARA TODOS LOS ROLES
  ADMIN_LOGIN: "ADMIN_LOGIN",
  ADMIN_LOGOUT: "ADMIN_LOGOUT",

  SUPERVISOR_LOGIN: "SUPERVISOR_LOGIN",
  SUPERVISOR_LOGOUT: "SUPERVISOR_LOGOUT",

  OPERATOR_LOGIN: "OPERATOR_LOGIN",
  OPERATOR_LOGOUT: "OPERATOR_LOGOUT",

  // SEGURIDAD
  SECURITY_FORBIDDEN_ACCESS: "SECURITY_FORBIDDEN_ACCESS",
  SECURITY_UNAUTHORIZED_ACCESS: "SECURITY_UNAUTHORIZED_ACCESS",
} as const;

export type AuditAction = typeof AuditActions[keyof typeof AuditActions];
